import './globals.css'
import {Analytics} from '@vercel/analytics/react';
import {config} from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false

export const runtime = 'edge';

export const metadata = {
  title: 'ADEPS Walks',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <main className="container">
      {children}
      <Analytics/>
    </main>
    </body>
    </html>
  )
}
